#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3000_Reload
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ChineseStudy")]
	public partial class ChineseStudyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insert_3000_Character(_3000_Character instance);
    partial void Update_3000_Character(_3000_Character instance);
    partial void Delete_3000_Character(_3000_Character instance);
    #endregion
		
		public ChineseStudyDataContext() : 
				base(global::_3000_Reload.Properties.Settings.Default.ChineseStudyConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ChineseStudyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChineseStudyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChineseStudyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChineseStudyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_3000_Character> _3000_Characters
		{
			get
			{
				return this.GetTable<_3000_Character>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_3000_Characters]")]
	public partial class _3000_Character : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FEseq;
		
		private string _Zhuyin;
		
		private string _Traditional;
		
		private string _English;
		
		private string _NumPinyin;
		
		private string _CritPinyin;
		
		private string _Simplified;
		
		private string _Cji;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFEseqChanging(string value);
    partial void OnFEseqChanged();
    partial void OnZhuyinChanging(string value);
    partial void OnZhuyinChanged();
    partial void OnTraditionalChanging(string value);
    partial void OnTraditionalChanged();
    partial void OnEnglishChanging(string value);
    partial void OnEnglishChanged();
    partial void OnNumPinyinChanging(string value);
    partial void OnNumPinyinChanged();
    partial void OnCritPinyinChanging(string value);
    partial void OnCritPinyinChanged();
    partial void OnSimplifiedChanging(string value);
    partial void OnSimplifiedChanged();
    partial void OnCjiChanging(string value);
    partial void OnCjiChanged();
    #endregion
		
		public _3000_Character()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEseq", DbType="NVarChar(255)")]
		public string FEseq
		{
			get
			{
				return this._FEseq;
			}
			set
			{
				if ((this._FEseq != value))
				{
					this.OnFEseqChanging(value);
					this.SendPropertyChanging();
					this._FEseq = value;
					this.SendPropertyChanged("FEseq");
					this.OnFEseqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zhuyin", DbType="NVarChar(255)")]
		public string Zhuyin
		{
			get
			{
				return this._Zhuyin;
			}
			set
			{
				if ((this._Zhuyin != value))
				{
					this.OnZhuyinChanging(value);
					this.SendPropertyChanging();
					this._Zhuyin = value;
					this.SendPropertyChanged("Zhuyin");
					this.OnZhuyinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Traditional", DbType="NVarChar(255)")]
		public string Traditional
		{
			get
			{
				return this._Traditional;
			}
			set
			{
				if ((this._Traditional != value))
				{
					this.OnTraditionalChanging(value);
					this.SendPropertyChanging();
					this._Traditional = value;
					this.SendPropertyChanged("Traditional");
					this.OnTraditionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_English", DbType="NVarChar(255)")]
		public string English
		{
			get
			{
				return this._English;
			}
			set
			{
				if ((this._English != value))
				{
					this.OnEnglishChanging(value);
					this.SendPropertyChanging();
					this._English = value;
					this.SendPropertyChanged("English");
					this.OnEnglishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumPinyin", DbType="NVarChar(255)")]
		public string NumPinyin
		{
			get
			{
				return this._NumPinyin;
			}
			set
			{
				if ((this._NumPinyin != value))
				{
					this.OnNumPinyinChanging(value);
					this.SendPropertyChanging();
					this._NumPinyin = value;
					this.SendPropertyChanged("NumPinyin");
					this.OnNumPinyinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CritPinyin", DbType="NVarChar(255)")]
		public string CritPinyin
		{
			get
			{
				return this._CritPinyin;
			}
			set
			{
				if ((this._CritPinyin != value))
				{
					this.OnCritPinyinChanging(value);
					this.SendPropertyChanging();
					this._CritPinyin = value;
					this.SendPropertyChanged("CritPinyin");
					this.OnCritPinyinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Simplified", DbType="NVarChar(255)")]
		public string Simplified
		{
			get
			{
				return this._Simplified;
			}
			set
			{
				if ((this._Simplified != value))
				{
					this.OnSimplifiedChanging(value);
					this.SendPropertyChanging();
					this._Simplified = value;
					this.SendPropertyChanged("Simplified");
					this.OnSimplifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cji", DbType="NVarChar(255)")]
		public string Cji
		{
			get
			{
				return this._Cji;
			}
			set
			{
				if ((this._Cji != value))
				{
					this.OnCjiChanging(value);
					this.SendPropertyChanging();
					this._Cji = value;
					this.SendPropertyChanged("Cji");
					this.OnCjiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
